{
 "title": "Harbour (Jolla Store)",
 "tags": [
  "harbour",
  "jolla",
  "sailfishos"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "3h",
 "panels": [
  { "title": "Harbour Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Installs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(harbour_total_installs[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Installs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(harbour_active_installs[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(harbour_app_qa_state[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Likes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(harbour_total_likes[2h])"
    }
   ]
  },
  {
   "title": "Total Reviews",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(harbour_total_reviews[2h])"
    }
   ]
  },
  { "title": "Applications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(harbour_app_downloads[2h])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Active installs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(harbour_app_active_installs[2h])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Likes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(harbour_app_likes[2h])",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "Reviews",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(harbour_app_reviews[2h])",
     "legendFormat": "{{app_name}}"
    }
   ]
  }
 ]
}